### ISSUE TITLE
Web Platform Tests

### ISSUE THREAD

**Issue by kflansburg** [cloudflare/workerd#2862]
- [X] [PR #2585] Initial scaffolding (bazel test autodiscovery, test harness, a couple of URL test cases)
- [X] [PR #3002] url tests
- [X] [PR #3030] urlpattern tests 
- [X] [PR #3076] Autogenerate `-test.js` file so that we don't miss out on new WPT cases as they're added. Config in `test-config.js`.
- [X] ["] Document how to add wpt test suites
- [ ] Investigate failing url tests
- [ ] Investigate failing urlpattern tests
- [ ] Later: add more test suites

**Comment by anonrig** [comment]
@npaun It seems `assert_throws_js` implementation is wrong. Here's the Node.js implementation: https://github.com/nodejs/node/blob/8807549ed9f6eaf6842ae56b8ac55ab385951636/test/fixtures/wpt/resources/testharness.js#L2046

**Comment by anonrig** [comment]
Additional issue: @npaun If a test is in `expected_failures` but if it doesn't fail, we should also throw an error.

**Comment by npaun** [comment]
Yep that's an excellent idea.
